# Introduction {-}

<!-- (Nicolas) Introduction to the workshop (5 min) -->

This workshops aims to provide the very basics of R to newcomers and a first 
introduction to spatial data handling in R using the [R-spatial ecosystem](https://cran.r-project.org/view=Spatial). 
We will present to the audience mapping with the {tmap} package, vector data
handling with {sf} and raster data handling with {terra}.

No previous knowledge of R is required.

The workshop leaders are [Nicolas Roelandt](https://roelandtn.frama.io/) from Gustave Eiffel university (Lyon, France) and [Jakub Nowosad](https://jakubnowosad.com/) from Adam Mickiewicz University (Poznań, Poland).

## Schedule {-}

- Opening the workshop (5 min)
- Introduction to R (15 min)
- Non-spatial data handling (30 min)
- Introduction to the R-spatial ecosystem (20 min)
- Mapping in R with {tmap} (30 min)
- Coffee break (to be confirmed)
- Vector data processing (45 min)
- Raster data processing (45 min)
- Closing the workshop (5 min)

## Pre-requisites {-}


1. A working installation of R (following [CRAN recommandations](https://cran.r-project.org/) for your computer)

:::: {.infobox .note data-latex="note"}

R comes with the RGui interface.
It is usable but for a better user experience we recommend using [Rstudio](https://www.rstudio.com/products/rstudio/download/#download).

<!--vscode??-->
[Jupyter Notebook](https://jupyter.org/) with the [IRKernel](https://irkernel.github.io/installation/) can also be a good option.

::::

2. R packages

Please run those commands into the R console:

```{r pre-requisites-packages, eval = FALSE}
packages <- c(
  gapminder,
  tmaptools,
  tmap,
  spData,
  sf,
  terra,
  fields,
  supercells,
  here)

# Install packages from CRAN Repo
install.packages(packages)

# Install spDataLarge that is not on CRAN repo
install.packages("spDataLarge", repos = "https://geocompr.r-universe.dev")
```

## What is ~~love~~ R ? {-}
<!-- (Nicolas) Introduction to R (15 min) -->

R is a programming language dedicated to data science.
It can compute statistics and produce graphics and reports (and much more).

It was created by Ross Ihaka and Robert Gentleman in 1993 and was released as a 
Free and Open Source Software in 1995.

## Why an R workshop in a FOSS4G conference ?

While R is not dedicated to spatial analysis, there a several dozen of packages that provides
geospatial capabilities to the language.

- Use R a standalone GIS:
  - read and write geospatial data
  - connect to geospatial data base
  - perform spatial analysis
  - make geostatistical modelling, prediction and simulation
  - access to algorithms from other tools ([QGIS](https://github.com/paleolimbot/qgisprocess), [GRASS](https://github.com/rsbivand/rgrass), [SAGA](https://github.com/stevenpawley/Rsagacmd))
- Use R in other FOSS4G tools:
  - [QGIS](https://docs.qgis.org/3.22/en/docs/training_manual/processing/r_intro.html?highlight=r%20processing)
  - [GRASS](https://grasswiki.osgeo.org/wiki/R_statistics)

## Coding paradigms {-}

When R was released, there was no strong syntax 
philosophy so there are some inconsistencies in packages, functions and arguments naming,
for example.
R base readability and performance where not good enough for some users so they
developed packages to improve those.

When using R for data analysis, you will encounter 3 majors coding paradigms:

- base R
- [Tidyverse](https://www.tidyverse.org/)
- [data.table](https://rdatatable.gitlab.io/data.table/)

Base R is a vanilla R code. The tidyverse aims to provide a more consistent grammar
 and readability.
 Data.table provides a fast and powerful alternative to R base with a consistent
 grammar.
 
You can mix those paradigms for your projects, but for teaching purposes the workshop 
materials will use tidyverse with some base R.
